version: '3.8'

services:
  db:
    image: postgres:14.5
    env_file:
      - ./.env
    ports:
      - 5432:5432

  redis:
    image: redis:alpine

  web:
    build:
        context: ./university
        dockerfile: Dockerfile
    command: bash -c "
        python manage.py makemigrations
        && python manage.py migrate
        && python manage.py initadmin
        && python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - ./university/:/usr/src/university/
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - redis
      - db

  celery:
    restart: always
    build:
      context: ./university
      dockerfile: Dockerfile
    command: celery -A university worker -l info
    volumes:
      - ./university/:/usr/src/university/
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - web